### ISSUE TITLE
A. Hide and Seek game

### ISSUE THREAD

**Issue by benrito** [Nolski/vroom-chicago-demo#10]
> It’s Monday, December 11th. Time for today’s game! Today, we’ll do Hide and Seek, which is great for children like [name]. Text “OK” to get started.

[[user confirms]]

[[MMS with hideandseek.mp4 and web link]]

> Let us know when you finish the activity! Did [name] like the activity? Text ‘yes’ or ‘no”

[[Yes]]

> Great! We’ll send you more like this.

[[No]]

> Sorry to hear it! Maybe [name] will like the next one better.

Wait 30 seconds, then go to B

**Comment by Nolski** [comment]
Just a heads up here: the MMS only supports video files < 10MB. I'll go ahead and ffmpeg resize these media assets until they're small enough

**Comment by benrito** [comment]
Perfect—these likely aren’t final assets, and in the end we’ll try to compress down as much as humanly possible. Thanks for ffmpeging in the meaning!

**Comment by Nolski** [comment]
Hey, just an update. After further research, 10MB is the twilio limit and different telecom providers have their own limits. (AT&T looks to be 500kb).
