### ISSUE TITLE
Command: 'appointment'

### ISSUE THREAD

**Issue by benrito** [Nolski/vroom-chicago-demo#14]
Reply:

Tonton’s friend will be coming to visit you tomorrow at 12:15! You can call this number if you need to reschedule: xxx-xxx-xxx.

**Comment by Nolski** [comment]
Should this actually schedule a thing? Given the demo length, probably not... but it's definitely possible :)

**Comment by benrito** [comment]
Was thinking just a dummy message, but we can mark that as a nice to have!
