### ISSUE TITLE
Command: 'help'

### ISSUE THREAD

**Issue by benrito** [Nolski/vroom-chicago-demo#16]

**Comment by benrito** [comment]
Reply:

Options:

1. Quit
2. Restart
3. About
4. Resume

**Comment by Nolski** [comment]
I noticed no about or resume command. Is this correct? Should we also list schedule and lullaby?

**Comment by benrito** [comment]
Ah! Good point. I'll add those now.

I was thinking of schedule and lullaby as easter eggs—the person leading the demo could use these to trigger the same actions that the flow would, but without going through the entire flow. (They shouldn't mess with the flow state, however)

**Comment by Nolski** [comment]
That works! There's a bit of a snag here. [According to twilio](https://support.twilio.com/hc/en-us/articles/223134027-Twilio-support-for-STOP-BLOCK-and-CANCEL-SMS-STOP-filtering-), it looks like words such as HELP, INFO, STOP, START, etc are reserved by twilio to ensure that users are being properly unsubscribed according to SMS industry standards. We could work around this by having something like *menu* for the help menu.

**Comment by Nolski** [comment]
This is also relevant to #9

**Comment by benrito** [comment]
Menu works
