### ISSUE TITLE
E. Initiate phone call — Bed Time Activity

### ISSUE THREAD

**Issue by Nolski** [Nolski/vroom-chicago-demo#8]
A bedtime activity!

>“It’s bedtime! Tonton has a new lullaby for [name]. Want her to call now? Text ‘yes’ or ‘no’”

[Yes]
initiate call

[No]
Wait 30 seconds, go to end demo flow

[Later]
Wait 30 seconds, go to E

**Comment by benrito** [comment]
If yes, initiate a phone call and play lullaby.m4a

**Comment by Nolski** [comment]
Are we still waiting on the audio asset for this? I have everything hooked up but I'm using a placeholder audio file for the time being.

**Comment by benrito** [comment]
I'll show this to Sesame to try and convince them to record us a lullaby in an Arabic muppet voice :)
