### ISSUE TITLE
End of Demo

### ISSUE THREAD

**Issue by Nolski** [Nolski/vroom-chicago-demo#9]
End of demo — 2 minutes after call

> “That’s all for the demo. To learn more, visit these links:”

 - Sesame Workshop landing?
 - Parenting in Displacement
 - Kofi Annan testimonial

> “You’ve been opted out. To restart the demo from the beginning, text *restart*

**Comment by benrito** [comment]
Let's make it immediately after they hang up from the call?

I'll get the final links ASAP. For now let's just use

http://sesameworkshop.org/refugee
